#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication surfaceFeatures

runApplication blockMesh

runApplication decomposePar -copyZero
runApplication snappyHexMesh -overwrite

runApplication patchSummary
#runApplication icoFoam
#runApplication $(getApplication)

#runApplication reconstructParMesh -constant
#runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
